version: "3"
services:
  markovserver:
    build: django
    volumes:
      - ./log/gunicorn:/app/log/gunicorn
    command: >
      /bin/bash -c "
      python manage.py migrate &&
      gunicorn -c /app/gunicorn.py tweet_generator.wsgi"
    env_file:
      - .conf/docker.env
    environment:
      TZ: Asia/Tokyo
    restart: always
  nuxt:
    build: nuxt
    restart: always
  nginx:
    build: nginx
    ports:
      - 80:80
    environment:
      TZ: Asia/Tokyo
    restart: always
